---

# Kubernetes setup
k8s_master_ip: "10.0.0.238"
pod_network_cidr: "10.0.200.0/24"
pod_network_manifest_file: "https://docs.projectcalico.org/manifests/calico.yaml"
rbac_manifest_file: "https://raw.githubusercontent.com/SmartGuyy/Ansible-P7-P13/master/kubernetes-cluster/rbac-kdd.yaml"
