name: install PHP
hosts: wordpress
apt: name={{item}} state=present
with_items:
    - php
    - php-mcrypt
    - php-mysql
    - php-common
    - php-mysql
    - php-tidy
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-memcached
    - php-curl
    - php-zip